version: '3'

services:
  mysql:
    container_name: mysql1
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mysql1    # MySQL 데이터베이스 이름
      MYSQL_USER: lee           # MySQL 사용자 이름
      MYSQL_PASSWORD: 1234      # MySQL 사용자 비밀번호
      MYSQL_ROOT_PASSWORD: 1234 # MySQL 루트 비밀번호
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"             # 호스트와 컨테이너의 포트 매핑
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d  # MySQL 설정 파일 위치 (필요시 추가)
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - app_network

  backend:
    container_name: backend
    build:
      context: ./                # 현재 디렉토리에서 Dockerfile을 참조
      dockerfile: Dockerfile      # 사용할 Dockerfile의 경로
    env_file:
      - .env                     # 환경 변수 파일
    ports:
      - "8080:8080"              # 백엔드 애플리케이션의 포트 매핑
    depends_on:
      - mysql                    # mysql 서비스가 시작된 후에 실행
    networks:
      - app_network

  redis:
    container_name: redis
    image: redis:latest          # Redis의 최신 버전
    ports:
      - "6379:6379"              # Redis 기본 포트 매핑
    networks:
      - app_network

networks:
  app_network:
    driver: bridge                # 기본적으로 브릿지 네트워크 사용
